name: python-fortran
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - setuptools
  - numpy
  - matplotlib
  - scipy
  - cython
  - sympy
  - pandas
  - jupyter
  - jupytext
  - fortran-magic 
  - cython 
  - numba
  - tqdm
  - imageio
  - pillow
  - pythran
  - ipywidgets
  - pip
  - pip:
     - julia
