name: python-fortran
channels:
  - conda-forge
dependencies:
  - python=3.9
  - cython
  - fortran-magic
  - fftw
  - gast
  - imageio
  - ipykernel
  - ipywidgets
  - jupytext
  - jupyter-book
  - matplotlib
  - meson
  - numba
  - numpy
  - pillow
  - pyjulia
  - pythran
  - scipy
  - seaborn
  - tqdm
