name: python-fortran
channels:
  - conda-forge
dependencies:
  - fortran-magic
  - imageio
  - ipykernel
  - ipywidgets
  - jupyter
  - jupytext
  - matplotlib
  - numba
  - numpy
  - pandas
  - pillow
  - pythran
  - scipy
  - seaborn
  - setuptools
  - tqdm
  - pip
  - pip:
    - julia
    - jupyter-book
