name: deploy-book

on:
  push:
    branches:
    - master

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - name: Install apt dependencies
      run: |
        sudo apt-get install -yq gfortran libfftw3-dev liblapack-dev

    - uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: goanpeca/setup-miniconda@v1
      with:
        miniconda-version: "latest"

    - name: Install dependencies and build the book
      shell: bash -l {0}
      run: |
        conda env create -f environment.yml -n runenv
        conda run -n runenv python -m ipykernel install --user --name python3
        conda run -n runenv jupyter-book build notebooks

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.SITE_PRIV }}
        publish_dir: ./docs/_build/html
