name: deploy-book

on:
  push:
    branches:
    - master

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - name: Install apt dependencies
      run: |
        sudo apt-get install -yq gfortran libatlas-base-dev libfftw3-dev
        sudo apt-get install -yq libopenblas-dev
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install jupyter-book
        pip install -r requirements.txt

    - name: Build the book
      run: |
        jupyter-book build docs

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.SITE_PRIV }}
        publish_dir: ./docs/_build/html
