name: jupyter-book

on:
  push:
    branches:
    - master

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt-get install -y libfftw-dev libopenblas-dev ffmpeg python3 python3-swig

    - uses: actions/checkout@v2

    - name: Install python dependencies
      run: pip3 install --user -r requirements.txt

    - name: Install Julia packages
      run: julia -e ' using Pkg; Pkg.add(["REPL", "PyCall"]); Pkg.build("PyCall")'

    - name: Build the book
      run: jupyter-book build notebooks

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.SITE_PRIV }}
        publish_dir: ./notebooks/_build/html
