name: jupyter-book

on:
  push:
    branches:
    - master

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: fortran-lang/setup-fortran@v1
      with:
          compiler: gcc
          - name: Install fortran
    - name: Install LaPack
      run:
        sudo apt-get install libblas-dev liblapack-dev
      shell: bash
    - uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - uses: julia-actions/setup-julia@v2

    - name: Install python dependencies
      run: python -m pip install -r requirements.txt

    - name: Install Julia packages
      run: julia -e ' using Pkg; Pkg.add(["REPL", "PyCall"]); Pkg.build("PyCall")'

    - name: Build the book
      run: jupyter-book build notebooks

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./notebooks/_build/html
