name: jupyter-book

on:
  push:
    branches:
    - master

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3.0.4
      with:
        environment-file: environment.yml
        activate-environment: python-fortran
        python-version: 3.9
        auto-activate-base: false

    - name: Install PyCall
      run: |
        julia -e ' using Pkg; Pkg.add(["REPL", "PyCall"]); Pkg.build("PyCall")'

    - name: Build the book
      shell: bash -l {0}
      run: |
        jupyter-book build notebooks

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./notebooks/_build/html
