name: jupyter-book

on:
  push:
    branches:
    - master

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - uses: julia-actions/setup-julia@v2

    - name: Install python dependencies
      run: python -m pip install -r requirements.txt

    - name: Install Julia packages
      run: julia -e ' using Pkg; Pkg.add(["REPL", "PyCall"]); Pkg.build("PyCall")'

    - name: Build the book
      run: jupyter-book build notebooks

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.SITE_PRIV }}
        publish_dir: ./notebooks/_build/html
