name: deploy-book

on:
  push:
    branches:
    - master

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - name: Install apt dependencies
      run: |
        sudo apt-get install -yq libfftw3-dev 

    - uses: actions/checkout@v2

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda env create -f environment.yml -n runenv

    - name: Install Julia packages
      run: julia -e '
          using Pkg; Pkg.add(["REPL", "PyCall"]);
          ENV["PYTHON"]="/usr/share/miniconda3/envs/runenv/bin/python";
          Pkg.build("PyCall")'

    - name: Install jupyterbook and build the book
      shell: bash -l {0}
      run: |
        conda run -n runenv python -m ipykernel install --user --name python3
        conda run -n runenv jupyter-book build notebooks

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.SITE_PRIV }}
        publish_dir: ./docs/_build/html
