name: jupyter-book

on:
  push:
    branches:
    - master

jobs:
  deploy-book:
    runs-on: macos-latest
    steps:
    - name: Install brew dependencies
      run: brew install fftw openblas swig ffmpeg python@3.8

    - uses: actions/checkout@v2

    - name: Install python dependencies
      run: |
        cp .pythranrc /Users/runner
        /usr/local/opt/python@3.8/bin/pip3.8 install -r requirements.txt

    - name: Install Julia packages
      run: julia -e '
          using Pkg; Pkg.add(["REPL", "PyCall"]);
          ENV["PYTHON"]="/usr/local/opt/python@3.8/bin/python3";
          Pkg.build("PyCall")'

    - name: Build the book
      run: |
          python3 -m venv jb
          source jb/bin/activate
          python -m pip install jupyter-book
          jupyter-book build notebooks

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.SITE_PRIV }}
        publish_dir: ./notebooks/_build/html
