name: deploy-book

on:
  push:
    branches:
    - master

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - name: Install apt dependencies
      run: |
        sudo apt-get install -yq gfortran libfftw3-dev liblapack-dev

    - uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: goanpeca/setup-miniconda@v1.1.2
      with:
        environment-file: environment.yml
        activate-environment: python-fortran
        python-version: 3.8
        auto-activate-base: false

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda env update -f environment.yml -n python-fortran
        conda run -n python-fortran python -m ipykernel install --user --name python3

    - name: Build the book
      shell: bash -l {0}
      run: |
        conda run -n python-fortran python -m pip install -U pythran
        conda run -n python-fortran jupyter-book build docs

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.SITE_PRIV }}
        publish_dir: ./docs/_build/html
